// File generated by FlutterFire CLI (edited for iOS + Web).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ✅ ใช้ค่าของ Web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions not set for macOS.');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions not set for Windows.');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions not set for Linux.');
      default:
        throw UnsupportedError('This platform is not supported.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3KuGw-TdMZT0z4AEGvPtHJjRzwtx4BY',
    appId: '1:203044905421:android:0d6ad910027c693a6f6484',
    messagingSenderId: '203044905421',
    projectId: 'helpcare11-3b153',
    storageBucket: 'helpcare11-3b153.firebasestorage.app',
  );

  // ───────── ANDROID ─────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJz-rLC9iZy1ZcTo1BYTHkfchJ4XrCDfQ',
    appId: '1:203044905421:ios:94f83d9fdee297dc6f6484',
    messagingSenderId: '203044905421',
    projectId: 'helpcare11-3b153',
    storageBucket: 'helpcare11-3b153.firebasestorage.app',
    iosBundleId: 'com.example.helpcare',
  );

  // ─────────── iOS ───────────

  // ─────────── WEB ───────────
  // ⛳ ใส่ “ค่าจริง” จาก Firebase Console → Project settings → Your apps → Web (</>)

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAokPUiKn-4rkuAXa0MvDiDqT5tZViTBC0',
    appId: '1:203044905421:web:a642854f96f84d176f6484',
    messagingSenderId: '203044905421',
    projectId: 'helpcare11-3b153',
    authDomain: 'helpcare11-3b153.firebaseapp.com',
    storageBucket: 'helpcare11-3b153.firebasestorage.app',
    measurementId: 'G-7HCKD0D7D1',
  );

  // ห้ามใช้ค่าของ Android/iOS แทน
}